<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Skeleton</title>
    <link href="/frontend/dist/bundle.css?v=<?= filemtime(PROJECT_ROOT . '../frontend/dist/bundle.css') ?>" rel="stylesheet" type="text/css">
</head>
<body>
    <div class="page">
        <h1>Hello, World!</h1>
    </div>

    <script src="/frontend/dist/bundle.js?v=<?= filemtime(PROJECT_ROOT . '../frontend/dist/bundle.js') ?>"></script>
</body>
</html>

